package com.juntao.project_T.dao;

import com.juntao.project_T.entity.HttptestCases;
import com.juntao.project_T.entity.HttptestCasesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HttptestCasesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    int countByExample(HttptestCasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    int deleteByExample(HttptestCasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    int insert(HttptestCases record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    int insertSelective(HttptestCases record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    List<HttptestCases> selectByExample(HttptestCasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    HttptestCases selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HttptestCases record, @Param("example") HttptestCasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HttptestCases record, @Param("example") HttptestCasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HttptestCases record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HttptestCases record);
}