#默认使用配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/project_t
    username: juntao
    password: jjt20030439
    driver-class-name: com.mysql.jdbc.Driver

---

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.juntao.project_T.entity
  mapperLocations: classpath:com/juntao/project_T/mapping/*.xml
