package com.juntao.project_T.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HttptestCasesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    public HttptestCasesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("CREATED is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("CREATED is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("CREATED =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("CREATED <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("CREATED >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("CREATED <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("CREATED <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("CREATED in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("CREATED not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("CREATED between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("CREATED not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andTeamIdIsNull() {
            addCriterion("TEAM_ID is null");
            return (Criteria) this;
        }

        public Criteria andTeamIdIsNotNull() {
            addCriterion("TEAM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTeamIdEqualTo(Long value) {
            addCriterion("TEAM_ID =", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdNotEqualTo(Long value) {
            addCriterion("TEAM_ID <>", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdGreaterThan(Long value) {
            addCriterion("TEAM_ID >", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdGreaterThanOrEqualTo(Long value) {
            addCriterion("TEAM_ID >=", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdLessThan(Long value) {
            addCriterion("TEAM_ID <", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdLessThanOrEqualTo(Long value) {
            addCriterion("TEAM_ID <=", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdIn(List<Long> values) {
            addCriterion("TEAM_ID in", values, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdNotIn(List<Long> values) {
            addCriterion("TEAM_ID not in", values, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdBetween(Long value1, Long value2) {
            addCriterion("TEAM_ID between", value1, value2, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdNotBetween(Long value1, Long value2) {
            addCriterion("TEAM_ID not between", value1, value2, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamNameIsNull() {
            addCriterion("TEAM_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTeamNameIsNotNull() {
            addCriterion("TEAM_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTeamNameEqualTo(String value) {
            addCriterion("TEAM_NAME =", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotEqualTo(String value) {
            addCriterion("TEAM_NAME <>", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameGreaterThan(String value) {
            addCriterion("TEAM_NAME >", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameGreaterThanOrEqualTo(String value) {
            addCriterion("TEAM_NAME >=", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameLessThan(String value) {
            addCriterion("TEAM_NAME <", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameLessThanOrEqualTo(String value) {
            addCriterion("TEAM_NAME <=", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameLike(String value) {
            addCriterion("TEAM_NAME like", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotLike(String value) {
            addCriterion("TEAM_NAME not like", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameIn(List<String> values) {
            addCriterion("TEAM_NAME in", values, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotIn(List<String> values) {
            addCriterion("TEAM_NAME not in", values, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameBetween(String value1, String value2) {
            addCriterion("TEAM_NAME between", value1, value2, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotBetween(String value1, String value2) {
            addCriterion("TEAM_NAME not between", value1, value2, "teamName");
            return (Criteria) this;
        }

        public Criteria andInvTypeIsNull() {
            addCriterion("INV_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andInvTypeIsNotNull() {
            addCriterion("INV_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andInvTypeEqualTo(String value) {
            addCriterion("INV_TYPE =", value, "invType");
            return (Criteria) this;
        }

        public Criteria andInvTypeNotEqualTo(String value) {
            addCriterion("INV_TYPE <>", value, "invType");
            return (Criteria) this;
        }

        public Criteria andInvTypeGreaterThan(String value) {
            addCriterion("INV_TYPE >", value, "invType");
            return (Criteria) this;
        }

        public Criteria andInvTypeGreaterThanOrEqualTo(String value) {
            addCriterion("INV_TYPE >=", value, "invType");
            return (Criteria) this;
        }

        public Criteria andInvTypeLessThan(String value) {
            addCriterion("INV_TYPE <", value, "invType");
            return (Criteria) this;
        }

        public Criteria andInvTypeLessThanOrEqualTo(String value) {
            addCriterion("INV_TYPE <=", value, "invType");
            return (Criteria) this;
        }

        public Criteria andInvTypeLike(String value) {
            addCriterion("INV_TYPE like", value, "invType");
            return (Criteria) this;
        }

        public Criteria andInvTypeNotLike(String value) {
            addCriterion("INV_TYPE not like", value, "invType");
            return (Criteria) this;
        }

        public Criteria andInvTypeIn(List<String> values) {
            addCriterion("INV_TYPE in", values, "invType");
            return (Criteria) this;
        }

        public Criteria andInvTypeNotIn(List<String> values) {
            addCriterion("INV_TYPE not in", values, "invType");
            return (Criteria) this;
        }

        public Criteria andInvTypeBetween(String value1, String value2) {
            addCriterion("INV_TYPE between", value1, value2, "invType");
            return (Criteria) this;
        }

        public Criteria andInvTypeNotBetween(String value1, String value2) {
            addCriterion("INV_TYPE not between", value1, value2, "invType");
            return (Criteria) this;
        }

        public Criteria andInvFieldIsNull() {
            addCriterion("INV_FIELD is null");
            return (Criteria) this;
        }

        public Criteria andInvFieldIsNotNull() {
            addCriterion("INV_FIELD is not null");
            return (Criteria) this;
        }

        public Criteria andInvFieldEqualTo(String value) {
            addCriterion("INV_FIELD =", value, "invField");
            return (Criteria) this;
        }

        public Criteria andInvFieldNotEqualTo(String value) {
            addCriterion("INV_FIELD <>", value, "invField");
            return (Criteria) this;
        }

        public Criteria andInvFieldGreaterThan(String value) {
            addCriterion("INV_FIELD >", value, "invField");
            return (Criteria) this;
        }

        public Criteria andInvFieldGreaterThanOrEqualTo(String value) {
            addCriterion("INV_FIELD >=", value, "invField");
            return (Criteria) this;
        }

        public Criteria andInvFieldLessThan(String value) {
            addCriterion("INV_FIELD <", value, "invField");
            return (Criteria) this;
        }

        public Criteria andInvFieldLessThanOrEqualTo(String value) {
            addCriterion("INV_FIELD <=", value, "invField");
            return (Criteria) this;
        }

        public Criteria andInvFieldLike(String value) {
            addCriterion("INV_FIELD like", value, "invField");
            return (Criteria) this;
        }

        public Criteria andInvFieldNotLike(String value) {
            addCriterion("INV_FIELD not like", value, "invField");
            return (Criteria) this;
        }

        public Criteria andInvFieldIn(List<String> values) {
            addCriterion("INV_FIELD in", values, "invField");
            return (Criteria) this;
        }

        public Criteria andInvFieldNotIn(List<String> values) {
            addCriterion("INV_FIELD not in", values, "invField");
            return (Criteria) this;
        }

        public Criteria andInvFieldBetween(String value1, String value2) {
            addCriterion("INV_FIELD between", value1, value2, "invField");
            return (Criteria) this;
        }

        public Criteria andInvFieldNotBetween(String value1, String value2) {
            addCriterion("INV_FIELD not between", value1, value2, "invField");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("PROJECT_ID is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("PROJECT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Long value) {
            addCriterion("PROJECT_ID =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Long value) {
            addCriterion("PROJECT_ID <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Long value) {
            addCriterion("PROJECT_ID >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PROJECT_ID >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Long value) {
            addCriterion("PROJECT_ID <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Long value) {
            addCriterion("PROJECT_ID <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Long> values) {
            addCriterion("PROJECT_ID in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Long> values) {
            addCriterion("PROJECT_ID not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Long value1, Long value2) {
            addCriterion("PROJECT_ID between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Long value1, Long value2) {
            addCriterion("PROJECT_ID not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("PROJECT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("PROJECT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("PROJECT_NAME =", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("PROJECT_NAME <>", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("PROJECT_NAME >", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("PROJECT_NAME >=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("PROJECT_NAME <", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("PROJECT_NAME <=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("PROJECT_NAME like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("PROJECT_NAME not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("PROJECT_NAME in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("PROJECT_NAME not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("PROJECT_NAME between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("PROJECT_NAME not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectVersionIsNull() {
            addCriterion("PROJECT_VERSION is null");
            return (Criteria) this;
        }

        public Criteria andProjectVersionIsNotNull() {
            addCriterion("PROJECT_VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andProjectVersionEqualTo(String value) {
            addCriterion("PROJECT_VERSION =", value, "projectVersion");
            return (Criteria) this;
        }

        public Criteria andProjectVersionNotEqualTo(String value) {
            addCriterion("PROJECT_VERSION <>", value, "projectVersion");
            return (Criteria) this;
        }

        public Criteria andProjectVersionGreaterThan(String value) {
            addCriterion("PROJECT_VERSION >", value, "projectVersion");
            return (Criteria) this;
        }

        public Criteria andProjectVersionGreaterThanOrEqualTo(String value) {
            addCriterion("PROJECT_VERSION >=", value, "projectVersion");
            return (Criteria) this;
        }

        public Criteria andProjectVersionLessThan(String value) {
            addCriterion("PROJECT_VERSION <", value, "projectVersion");
            return (Criteria) this;
        }

        public Criteria andProjectVersionLessThanOrEqualTo(String value) {
            addCriterion("PROJECT_VERSION <=", value, "projectVersion");
            return (Criteria) this;
        }

        public Criteria andProjectVersionLike(String value) {
            addCriterion("PROJECT_VERSION like", value, "projectVersion");
            return (Criteria) this;
        }

        public Criteria andProjectVersionNotLike(String value) {
            addCriterion("PROJECT_VERSION not like", value, "projectVersion");
            return (Criteria) this;
        }

        public Criteria andProjectVersionIn(List<String> values) {
            addCriterion("PROJECT_VERSION in", values, "projectVersion");
            return (Criteria) this;
        }

        public Criteria andProjectVersionNotIn(List<String> values) {
            addCriterion("PROJECT_VERSION not in", values, "projectVersion");
            return (Criteria) this;
        }

        public Criteria andProjectVersionBetween(String value1, String value2) {
            addCriterion("PROJECT_VERSION between", value1, value2, "projectVersion");
            return (Criteria) this;
        }

        public Criteria andProjectVersionNotBetween(String value1, String value2) {
            addCriterion("PROJECT_VERSION not between", value1, value2, "projectVersion");
            return (Criteria) this;
        }

        public Criteria andApiNameIsNull() {
            addCriterion("API_NAME is null");
            return (Criteria) this;
        }

        public Criteria andApiNameIsNotNull() {
            addCriterion("API_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andApiNameEqualTo(String value) {
            addCriterion("API_NAME =", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameNotEqualTo(String value) {
            addCriterion("API_NAME <>", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameGreaterThan(String value) {
            addCriterion("API_NAME >", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameGreaterThanOrEqualTo(String value) {
            addCriterion("API_NAME >=", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameLessThan(String value) {
            addCriterion("API_NAME <", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameLessThanOrEqualTo(String value) {
            addCriterion("API_NAME <=", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameLike(String value) {
            addCriterion("API_NAME like", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameNotLike(String value) {
            addCriterion("API_NAME not like", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameIn(List<String> values) {
            addCriterion("API_NAME in", values, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameNotIn(List<String> values) {
            addCriterion("API_NAME not in", values, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameBetween(String value1, String value2) {
            addCriterion("API_NAME between", value1, value2, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameNotBetween(String value1, String value2) {
            addCriterion("API_NAME not between", value1, value2, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiCatalogIsNull() {
            addCriterion("API_CATALOG is null");
            return (Criteria) this;
        }

        public Criteria andApiCatalogIsNotNull() {
            addCriterion("API_CATALOG is not null");
            return (Criteria) this;
        }

        public Criteria andApiCatalogEqualTo(String value) {
            addCriterion("API_CATALOG =", value, "apiCatalog");
            return (Criteria) this;
        }

        public Criteria andApiCatalogNotEqualTo(String value) {
            addCriterion("API_CATALOG <>", value, "apiCatalog");
            return (Criteria) this;
        }

        public Criteria andApiCatalogGreaterThan(String value) {
            addCriterion("API_CATALOG >", value, "apiCatalog");
            return (Criteria) this;
        }

        public Criteria andApiCatalogGreaterThanOrEqualTo(String value) {
            addCriterion("API_CATALOG >=", value, "apiCatalog");
            return (Criteria) this;
        }

        public Criteria andApiCatalogLessThan(String value) {
            addCriterion("API_CATALOG <", value, "apiCatalog");
            return (Criteria) this;
        }

        public Criteria andApiCatalogLessThanOrEqualTo(String value) {
            addCriterion("API_CATALOG <=", value, "apiCatalog");
            return (Criteria) this;
        }

        public Criteria andApiCatalogLike(String value) {
            addCriterion("API_CATALOG like", value, "apiCatalog");
            return (Criteria) this;
        }

        public Criteria andApiCatalogNotLike(String value) {
            addCriterion("API_CATALOG not like", value, "apiCatalog");
            return (Criteria) this;
        }

        public Criteria andApiCatalogIn(List<String> values) {
            addCriterion("API_CATALOG in", values, "apiCatalog");
            return (Criteria) this;
        }

        public Criteria andApiCatalogNotIn(List<String> values) {
            addCriterion("API_CATALOG not in", values, "apiCatalog");
            return (Criteria) this;
        }

        public Criteria andApiCatalogBetween(String value1, String value2) {
            addCriterion("API_CATALOG between", value1, value2, "apiCatalog");
            return (Criteria) this;
        }

        public Criteria andApiCatalogNotBetween(String value1, String value2) {
            addCriterion("API_CATALOG not between", value1, value2, "apiCatalog");
            return (Criteria) this;
        }

        public Criteria andHttpMethodIsNull() {
            addCriterion("HTTP_METHOD is null");
            return (Criteria) this;
        }

        public Criteria andHttpMethodIsNotNull() {
            addCriterion("HTTP_METHOD is not null");
            return (Criteria) this;
        }

        public Criteria andHttpMethodEqualTo(String value) {
            addCriterion("HTTP_METHOD =", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodNotEqualTo(String value) {
            addCriterion("HTTP_METHOD <>", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodGreaterThan(String value) {
            addCriterion("HTTP_METHOD >", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodGreaterThanOrEqualTo(String value) {
            addCriterion("HTTP_METHOD >=", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodLessThan(String value) {
            addCriterion("HTTP_METHOD <", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodLessThanOrEqualTo(String value) {
            addCriterion("HTTP_METHOD <=", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodLike(String value) {
            addCriterion("HTTP_METHOD like", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodNotLike(String value) {
            addCriterion("HTTP_METHOD not like", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodIn(List<String> values) {
            addCriterion("HTTP_METHOD in", values, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodNotIn(List<String> values) {
            addCriterion("HTTP_METHOD not in", values, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodBetween(String value1, String value2) {
            addCriterion("HTTP_METHOD between", value1, value2, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodNotBetween(String value1, String value2) {
            addCriterion("HTTP_METHOD not between", value1, value2, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNull() {
            addCriterion("CONTENT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNotNull() {
            addCriterion("CONTENT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andContentTypeEqualTo(String value) {
            addCriterion("CONTENT_TYPE =", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotEqualTo(String value) {
            addCriterion("CONTENT_TYPE <>", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThan(String value) {
            addCriterion("CONTENT_TYPE >", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CONTENT_TYPE >=", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThan(String value) {
            addCriterion("CONTENT_TYPE <", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThanOrEqualTo(String value) {
            addCriterion("CONTENT_TYPE <=", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLike(String value) {
            addCriterion("CONTENT_TYPE like", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotLike(String value) {
            addCriterion("CONTENT_TYPE not like", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeIn(List<String> values) {
            addCriterion("CONTENT_TYPE in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotIn(List<String> values) {
            addCriterion("CONTENT_TYPE not in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeBetween(String value1, String value2) {
            addCriterion("CONTENT_TYPE between", value1, value2, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotBetween(String value1, String value2) {
            addCriterion("CONTENT_TYPE not between", value1, value2, "contentType");
            return (Criteria) this;
        }

        public Criteria andMasterCookieIsNull() {
            addCriterion("MASTER_COOKIE is null");
            return (Criteria) this;
        }

        public Criteria andMasterCookieIsNotNull() {
            addCriterion("MASTER_COOKIE is not null");
            return (Criteria) this;
        }

        public Criteria andMasterCookieEqualTo(String value) {
            addCriterion("MASTER_COOKIE =", value, "masterCookie");
            return (Criteria) this;
        }

        public Criteria andMasterCookieNotEqualTo(String value) {
            addCriterion("MASTER_COOKIE <>", value, "masterCookie");
            return (Criteria) this;
        }

        public Criteria andMasterCookieGreaterThan(String value) {
            addCriterion("MASTER_COOKIE >", value, "masterCookie");
            return (Criteria) this;
        }

        public Criteria andMasterCookieGreaterThanOrEqualTo(String value) {
            addCriterion("MASTER_COOKIE >=", value, "masterCookie");
            return (Criteria) this;
        }

        public Criteria andMasterCookieLessThan(String value) {
            addCriterion("MASTER_COOKIE <", value, "masterCookie");
            return (Criteria) this;
        }

        public Criteria andMasterCookieLessThanOrEqualTo(String value) {
            addCriterion("MASTER_COOKIE <=", value, "masterCookie");
            return (Criteria) this;
        }

        public Criteria andMasterCookieLike(String value) {
            addCriterion("MASTER_COOKIE like", value, "masterCookie");
            return (Criteria) this;
        }

        public Criteria andMasterCookieNotLike(String value) {
            addCriterion("MASTER_COOKIE not like", value, "masterCookie");
            return (Criteria) this;
        }

        public Criteria andMasterCookieIn(List<String> values) {
            addCriterion("MASTER_COOKIE in", values, "masterCookie");
            return (Criteria) this;
        }

        public Criteria andMasterCookieNotIn(List<String> values) {
            addCriterion("MASTER_COOKIE not in", values, "masterCookie");
            return (Criteria) this;
        }

        public Criteria andMasterCookieBetween(String value1, String value2) {
            addCriterion("MASTER_COOKIE between", value1, value2, "masterCookie");
            return (Criteria) this;
        }

        public Criteria andMasterCookieNotBetween(String value1, String value2) {
            addCriterion("MASTER_COOKIE not between", value1, value2, "masterCookie");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlFlagIsNull() {
            addCriterion("PRE_UPDATE_SQL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlFlagIsNotNull() {
            addCriterion("PRE_UPDATE_SQL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlFlagEqualTo(String value) {
            addCriterion("PRE_UPDATE_SQL_FLAG =", value, "preUpdateSqlFlag");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlFlagNotEqualTo(String value) {
            addCriterion("PRE_UPDATE_SQL_FLAG <>", value, "preUpdateSqlFlag");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlFlagGreaterThan(String value) {
            addCriterion("PRE_UPDATE_SQL_FLAG >", value, "preUpdateSqlFlag");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlFlagGreaterThanOrEqualTo(String value) {
            addCriterion("PRE_UPDATE_SQL_FLAG >=", value, "preUpdateSqlFlag");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlFlagLessThan(String value) {
            addCriterion("PRE_UPDATE_SQL_FLAG <", value, "preUpdateSqlFlag");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlFlagLessThanOrEqualTo(String value) {
            addCriterion("PRE_UPDATE_SQL_FLAG <=", value, "preUpdateSqlFlag");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlFlagLike(String value) {
            addCriterion("PRE_UPDATE_SQL_FLAG like", value, "preUpdateSqlFlag");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlFlagNotLike(String value) {
            addCriterion("PRE_UPDATE_SQL_FLAG not like", value, "preUpdateSqlFlag");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlFlagIn(List<String> values) {
            addCriterion("PRE_UPDATE_SQL_FLAG in", values, "preUpdateSqlFlag");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlFlagNotIn(List<String> values) {
            addCriterion("PRE_UPDATE_SQL_FLAG not in", values, "preUpdateSqlFlag");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlFlagBetween(String value1, String value2) {
            addCriterion("PRE_UPDATE_SQL_FLAG between", value1, value2, "preUpdateSqlFlag");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlFlagNotBetween(String value1, String value2) {
            addCriterion("PRE_UPDATE_SQL_FLAG not between", value1, value2, "preUpdateSqlFlag");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlIsNull() {
            addCriterion("PRE_UPDATE_SQL is null");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlIsNotNull() {
            addCriterion("PRE_UPDATE_SQL is not null");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlEqualTo(String value) {
            addCriterion("PRE_UPDATE_SQL =", value, "preUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlNotEqualTo(String value) {
            addCriterion("PRE_UPDATE_SQL <>", value, "preUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlGreaterThan(String value) {
            addCriterion("PRE_UPDATE_SQL >", value, "preUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlGreaterThanOrEqualTo(String value) {
            addCriterion("PRE_UPDATE_SQL >=", value, "preUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlLessThan(String value) {
            addCriterion("PRE_UPDATE_SQL <", value, "preUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlLessThanOrEqualTo(String value) {
            addCriterion("PRE_UPDATE_SQL <=", value, "preUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlLike(String value) {
            addCriterion("PRE_UPDATE_SQL like", value, "preUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlNotLike(String value) {
            addCriterion("PRE_UPDATE_SQL not like", value, "preUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlIn(List<String> values) {
            addCriterion("PRE_UPDATE_SQL in", values, "preUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlNotIn(List<String> values) {
            addCriterion("PRE_UPDATE_SQL not in", values, "preUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlBetween(String value1, String value2) {
            addCriterion("PRE_UPDATE_SQL between", value1, value2, "preUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPreUpdateSqlNotBetween(String value1, String value2) {
            addCriterion("PRE_UPDATE_SQL not between", value1, value2, "preUpdateSql");
            return (Criteria) this;
        }

        public Criteria andTestPurposeIsNull() {
            addCriterion("TEST_PURPOSE is null");
            return (Criteria) this;
        }

        public Criteria andTestPurposeIsNotNull() {
            addCriterion("TEST_PURPOSE is not null");
            return (Criteria) this;
        }

        public Criteria andTestPurposeEqualTo(String value) {
            addCriterion("TEST_PURPOSE =", value, "testPurpose");
            return (Criteria) this;
        }

        public Criteria andTestPurposeNotEqualTo(String value) {
            addCriterion("TEST_PURPOSE <>", value, "testPurpose");
            return (Criteria) this;
        }

        public Criteria andTestPurposeGreaterThan(String value) {
            addCriterion("TEST_PURPOSE >", value, "testPurpose");
            return (Criteria) this;
        }

        public Criteria andTestPurposeGreaterThanOrEqualTo(String value) {
            addCriterion("TEST_PURPOSE >=", value, "testPurpose");
            return (Criteria) this;
        }

        public Criteria andTestPurposeLessThan(String value) {
            addCriterion("TEST_PURPOSE <", value, "testPurpose");
            return (Criteria) this;
        }

        public Criteria andTestPurposeLessThanOrEqualTo(String value) {
            addCriterion("TEST_PURPOSE <=", value, "testPurpose");
            return (Criteria) this;
        }

        public Criteria andTestPurposeLike(String value) {
            addCriterion("TEST_PURPOSE like", value, "testPurpose");
            return (Criteria) this;
        }

        public Criteria andTestPurposeNotLike(String value) {
            addCriterion("TEST_PURPOSE not like", value, "testPurpose");
            return (Criteria) this;
        }

        public Criteria andTestPurposeIn(List<String> values) {
            addCriterion("TEST_PURPOSE in", values, "testPurpose");
            return (Criteria) this;
        }

        public Criteria andTestPurposeNotIn(List<String> values) {
            addCriterion("TEST_PURPOSE not in", values, "testPurpose");
            return (Criteria) this;
        }

        public Criteria andTestPurposeBetween(String value1, String value2) {
            addCriterion("TEST_PURPOSE between", value1, value2, "testPurpose");
            return (Criteria) this;
        }

        public Criteria andTestPurposeNotBetween(String value1, String value2) {
            addCriterion("TEST_PURPOSE not between", value1, value2, "testPurpose");
            return (Criteria) this;
        }

        public Criteria andTestCaseDescriptionIsNull() {
            addCriterion("TEST_CASE_DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andTestCaseDescriptionIsNotNull() {
            addCriterion("TEST_CASE_DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andTestCaseDescriptionEqualTo(String value) {
            addCriterion("TEST_CASE_DESCRIPTION =", value, "testCaseDescription");
            return (Criteria) this;
        }

        public Criteria andTestCaseDescriptionNotEqualTo(String value) {
            addCriterion("TEST_CASE_DESCRIPTION <>", value, "testCaseDescription");
            return (Criteria) this;
        }

        public Criteria andTestCaseDescriptionGreaterThan(String value) {
            addCriterion("TEST_CASE_DESCRIPTION >", value, "testCaseDescription");
            return (Criteria) this;
        }

        public Criteria andTestCaseDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("TEST_CASE_DESCRIPTION >=", value, "testCaseDescription");
            return (Criteria) this;
        }

        public Criteria andTestCaseDescriptionLessThan(String value) {
            addCriterion("TEST_CASE_DESCRIPTION <", value, "testCaseDescription");
            return (Criteria) this;
        }

        public Criteria andTestCaseDescriptionLessThanOrEqualTo(String value) {
            addCriterion("TEST_CASE_DESCRIPTION <=", value, "testCaseDescription");
            return (Criteria) this;
        }

        public Criteria andTestCaseDescriptionLike(String value) {
            addCriterion("TEST_CASE_DESCRIPTION like", value, "testCaseDescription");
            return (Criteria) this;
        }

        public Criteria andTestCaseDescriptionNotLike(String value) {
            addCriterion("TEST_CASE_DESCRIPTION not like", value, "testCaseDescription");
            return (Criteria) this;
        }

        public Criteria andTestCaseDescriptionIn(List<String> values) {
            addCriterion("TEST_CASE_DESCRIPTION in", values, "testCaseDescription");
            return (Criteria) this;
        }

        public Criteria andTestCaseDescriptionNotIn(List<String> values) {
            addCriterion("TEST_CASE_DESCRIPTION not in", values, "testCaseDescription");
            return (Criteria) this;
        }

        public Criteria andTestCaseDescriptionBetween(String value1, String value2) {
            addCriterion("TEST_CASE_DESCRIPTION between", value1, value2, "testCaseDescription");
            return (Criteria) this;
        }

        public Criteria andTestCaseDescriptionNotBetween(String value1, String value2) {
            addCriterion("TEST_CASE_DESCRIPTION not between", value1, value2, "testCaseDescription");
            return (Criteria) this;
        }

        public Criteria andTestCaseKeySetIsNull() {
            addCriterion("TEST_CASE_KEY_SET is null");
            return (Criteria) this;
        }

        public Criteria andTestCaseKeySetIsNotNull() {
            addCriterion("TEST_CASE_KEY_SET is not null");
            return (Criteria) this;
        }

        public Criteria andTestCaseKeySetEqualTo(String value) {
            addCriterion("TEST_CASE_KEY_SET =", value, "testCaseKeySet");
            return (Criteria) this;
        }

        public Criteria andTestCaseKeySetNotEqualTo(String value) {
            addCriterion("TEST_CASE_KEY_SET <>", value, "testCaseKeySet");
            return (Criteria) this;
        }

        public Criteria andTestCaseKeySetGreaterThan(String value) {
            addCriterion("TEST_CASE_KEY_SET >", value, "testCaseKeySet");
            return (Criteria) this;
        }

        public Criteria andTestCaseKeySetGreaterThanOrEqualTo(String value) {
            addCriterion("TEST_CASE_KEY_SET >=", value, "testCaseKeySet");
            return (Criteria) this;
        }

        public Criteria andTestCaseKeySetLessThan(String value) {
            addCriterion("TEST_CASE_KEY_SET <", value, "testCaseKeySet");
            return (Criteria) this;
        }

        public Criteria andTestCaseKeySetLessThanOrEqualTo(String value) {
            addCriterion("TEST_CASE_KEY_SET <=", value, "testCaseKeySet");
            return (Criteria) this;
        }

        public Criteria andTestCaseKeySetLike(String value) {
            addCriterion("TEST_CASE_KEY_SET like", value, "testCaseKeySet");
            return (Criteria) this;
        }

        public Criteria andTestCaseKeySetNotLike(String value) {
            addCriterion("TEST_CASE_KEY_SET not like", value, "testCaseKeySet");
            return (Criteria) this;
        }

        public Criteria andTestCaseKeySetIn(List<String> values) {
            addCriterion("TEST_CASE_KEY_SET in", values, "testCaseKeySet");
            return (Criteria) this;
        }

        public Criteria andTestCaseKeySetNotIn(List<String> values) {
            addCriterion("TEST_CASE_KEY_SET not in", values, "testCaseKeySet");
            return (Criteria) this;
        }

        public Criteria andTestCaseKeySetBetween(String value1, String value2) {
            addCriterion("TEST_CASE_KEY_SET between", value1, value2, "testCaseKeySet");
            return (Criteria) this;
        }

        public Criteria andTestCaseKeySetNotBetween(String value1, String value2) {
            addCriterion("TEST_CASE_KEY_SET not between", value1, value2, "testCaseKeySet");
            return (Criteria) this;
        }

        public Criteria andTestCaseValueSetIsNull() {
            addCriterion("TEST_CASE_VALUE_SET is null");
            return (Criteria) this;
        }

        public Criteria andTestCaseValueSetIsNotNull() {
            addCriterion("TEST_CASE_VALUE_SET is not null");
            return (Criteria) this;
        }

        public Criteria andTestCaseValueSetEqualTo(String value) {
            addCriterion("TEST_CASE_VALUE_SET =", value, "testCaseValueSet");
            return (Criteria) this;
        }

        public Criteria andTestCaseValueSetNotEqualTo(String value) {
            addCriterion("TEST_CASE_VALUE_SET <>", value, "testCaseValueSet");
            return (Criteria) this;
        }

        public Criteria andTestCaseValueSetGreaterThan(String value) {
            addCriterion("TEST_CASE_VALUE_SET >", value, "testCaseValueSet");
            return (Criteria) this;
        }

        public Criteria andTestCaseValueSetGreaterThanOrEqualTo(String value) {
            addCriterion("TEST_CASE_VALUE_SET >=", value, "testCaseValueSet");
            return (Criteria) this;
        }

        public Criteria andTestCaseValueSetLessThan(String value) {
            addCriterion("TEST_CASE_VALUE_SET <", value, "testCaseValueSet");
            return (Criteria) this;
        }

        public Criteria andTestCaseValueSetLessThanOrEqualTo(String value) {
            addCriterion("TEST_CASE_VALUE_SET <=", value, "testCaseValueSet");
            return (Criteria) this;
        }

        public Criteria andTestCaseValueSetLike(String value) {
            addCriterion("TEST_CASE_VALUE_SET like", value, "testCaseValueSet");
            return (Criteria) this;
        }

        public Criteria andTestCaseValueSetNotLike(String value) {
            addCriterion("TEST_CASE_VALUE_SET not like", value, "testCaseValueSet");
            return (Criteria) this;
        }

        public Criteria andTestCaseValueSetIn(List<String> values) {
            addCriterion("TEST_CASE_VALUE_SET in", values, "testCaseValueSet");
            return (Criteria) this;
        }

        public Criteria andTestCaseValueSetNotIn(List<String> values) {
            addCriterion("TEST_CASE_VALUE_SET not in", values, "testCaseValueSet");
            return (Criteria) this;
        }

        public Criteria andTestCaseValueSetBetween(String value1, String value2) {
            addCriterion("TEST_CASE_VALUE_SET between", value1, value2, "testCaseValueSet");
            return (Criteria) this;
        }

        public Criteria andTestCaseValueSetNotBetween(String value1, String value2) {
            addCriterion("TEST_CASE_VALUE_SET not between", value1, value2, "testCaseValueSet");
            return (Criteria) this;
        }

        public Criteria andUploadFilePathIsNull() {
            addCriterion("UPLOAD_FILE_PATH is null");
            return (Criteria) this;
        }

        public Criteria andUploadFilePathIsNotNull() {
            addCriterion("UPLOAD_FILE_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andUploadFilePathEqualTo(String value) {
            addCriterion("UPLOAD_FILE_PATH =", value, "uploadFilePath");
            return (Criteria) this;
        }

        public Criteria andUploadFilePathNotEqualTo(String value) {
            addCriterion("UPLOAD_FILE_PATH <>", value, "uploadFilePath");
            return (Criteria) this;
        }

        public Criteria andUploadFilePathGreaterThan(String value) {
            addCriterion("UPLOAD_FILE_PATH >", value, "uploadFilePath");
            return (Criteria) this;
        }

        public Criteria andUploadFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("UPLOAD_FILE_PATH >=", value, "uploadFilePath");
            return (Criteria) this;
        }

        public Criteria andUploadFilePathLessThan(String value) {
            addCriterion("UPLOAD_FILE_PATH <", value, "uploadFilePath");
            return (Criteria) this;
        }

        public Criteria andUploadFilePathLessThanOrEqualTo(String value) {
            addCriterion("UPLOAD_FILE_PATH <=", value, "uploadFilePath");
            return (Criteria) this;
        }

        public Criteria andUploadFilePathLike(String value) {
            addCriterion("UPLOAD_FILE_PATH like", value, "uploadFilePath");
            return (Criteria) this;
        }

        public Criteria andUploadFilePathNotLike(String value) {
            addCriterion("UPLOAD_FILE_PATH not like", value, "uploadFilePath");
            return (Criteria) this;
        }

        public Criteria andUploadFilePathIn(List<String> values) {
            addCriterion("UPLOAD_FILE_PATH in", values, "uploadFilePath");
            return (Criteria) this;
        }

        public Criteria andUploadFilePathNotIn(List<String> values) {
            addCriterion("UPLOAD_FILE_PATH not in", values, "uploadFilePath");
            return (Criteria) this;
        }

        public Criteria andUploadFilePathBetween(String value1, String value2) {
            addCriterion("UPLOAD_FILE_PATH between", value1, value2, "uploadFilePath");
            return (Criteria) this;
        }

        public Criteria andUploadFilePathNotBetween(String value1, String value2) {
            addCriterion("UPLOAD_FILE_PATH not between", value1, value2, "uploadFilePath");
            return (Criteria) this;
        }

        public Criteria andDownloadFilePathIsNull() {
            addCriterion("DOWNLOAD_FILE_PATH is null");
            return (Criteria) this;
        }

        public Criteria andDownloadFilePathIsNotNull() {
            addCriterion("DOWNLOAD_FILE_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andDownloadFilePathEqualTo(String value) {
            addCriterion("DOWNLOAD_FILE_PATH =", value, "downloadFilePath");
            return (Criteria) this;
        }

        public Criteria andDownloadFilePathNotEqualTo(String value) {
            addCriterion("DOWNLOAD_FILE_PATH <>", value, "downloadFilePath");
            return (Criteria) this;
        }

        public Criteria andDownloadFilePathGreaterThan(String value) {
            addCriterion("DOWNLOAD_FILE_PATH >", value, "downloadFilePath");
            return (Criteria) this;
        }

        public Criteria andDownloadFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("DOWNLOAD_FILE_PATH >=", value, "downloadFilePath");
            return (Criteria) this;
        }

        public Criteria andDownloadFilePathLessThan(String value) {
            addCriterion("DOWNLOAD_FILE_PATH <", value, "downloadFilePath");
            return (Criteria) this;
        }

        public Criteria andDownloadFilePathLessThanOrEqualTo(String value) {
            addCriterion("DOWNLOAD_FILE_PATH <=", value, "downloadFilePath");
            return (Criteria) this;
        }

        public Criteria andDownloadFilePathLike(String value) {
            addCriterion("DOWNLOAD_FILE_PATH like", value, "downloadFilePath");
            return (Criteria) this;
        }

        public Criteria andDownloadFilePathNotLike(String value) {
            addCriterion("DOWNLOAD_FILE_PATH not like", value, "downloadFilePath");
            return (Criteria) this;
        }

        public Criteria andDownloadFilePathIn(List<String> values) {
            addCriterion("DOWNLOAD_FILE_PATH in", values, "downloadFilePath");
            return (Criteria) this;
        }

        public Criteria andDownloadFilePathNotIn(List<String> values) {
            addCriterion("DOWNLOAD_FILE_PATH not in", values, "downloadFilePath");
            return (Criteria) this;
        }

        public Criteria andDownloadFilePathBetween(String value1, String value2) {
            addCriterion("DOWNLOAD_FILE_PATH between", value1, value2, "downloadFilePath");
            return (Criteria) this;
        }

        public Criteria andDownloadFilePathNotBetween(String value1, String value2) {
            addCriterion("DOWNLOAD_FILE_PATH not between", value1, value2, "downloadFilePath");
            return (Criteria) this;
        }

        public Criteria andAssertTypeSetIsNull() {
            addCriterion("ASSERT_TYPE_SET is null");
            return (Criteria) this;
        }

        public Criteria andAssertTypeSetIsNotNull() {
            addCriterion("ASSERT_TYPE_SET is not null");
            return (Criteria) this;
        }

        public Criteria andAssertTypeSetEqualTo(String value) {
            addCriterion("ASSERT_TYPE_SET =", value, "assertTypeSet");
            return (Criteria) this;
        }

        public Criteria andAssertTypeSetNotEqualTo(String value) {
            addCriterion("ASSERT_TYPE_SET <>", value, "assertTypeSet");
            return (Criteria) this;
        }

        public Criteria andAssertTypeSetGreaterThan(String value) {
            addCriterion("ASSERT_TYPE_SET >", value, "assertTypeSet");
            return (Criteria) this;
        }

        public Criteria andAssertTypeSetGreaterThanOrEqualTo(String value) {
            addCriterion("ASSERT_TYPE_SET >=", value, "assertTypeSet");
            return (Criteria) this;
        }

        public Criteria andAssertTypeSetLessThan(String value) {
            addCriterion("ASSERT_TYPE_SET <", value, "assertTypeSet");
            return (Criteria) this;
        }

        public Criteria andAssertTypeSetLessThanOrEqualTo(String value) {
            addCriterion("ASSERT_TYPE_SET <=", value, "assertTypeSet");
            return (Criteria) this;
        }

        public Criteria andAssertTypeSetLike(String value) {
            addCriterion("ASSERT_TYPE_SET like", value, "assertTypeSet");
            return (Criteria) this;
        }

        public Criteria andAssertTypeSetNotLike(String value) {
            addCriterion("ASSERT_TYPE_SET not like", value, "assertTypeSet");
            return (Criteria) this;
        }

        public Criteria andAssertTypeSetIn(List<String> values) {
            addCriterion("ASSERT_TYPE_SET in", values, "assertTypeSet");
            return (Criteria) this;
        }

        public Criteria andAssertTypeSetNotIn(List<String> values) {
            addCriterion("ASSERT_TYPE_SET not in", values, "assertTypeSet");
            return (Criteria) this;
        }

        public Criteria andAssertTypeSetBetween(String value1, String value2) {
            addCriterion("ASSERT_TYPE_SET between", value1, value2, "assertTypeSet");
            return (Criteria) this;
        }

        public Criteria andAssertTypeSetNotBetween(String value1, String value2) {
            addCriterion("ASSERT_TYPE_SET not between", value1, value2, "assertTypeSet");
            return (Criteria) this;
        }

        public Criteria andAssertJsonIsNull() {
            addCriterion("ASSERT_JSON is null");
            return (Criteria) this;
        }

        public Criteria andAssertJsonIsNotNull() {
            addCriterion("ASSERT_JSON is not null");
            return (Criteria) this;
        }

        public Criteria andAssertJsonEqualTo(Object value) {
            addCriterion("ASSERT_JSON =", value, "assertJson");
            return (Criteria) this;
        }

        public Criteria andAssertJsonNotEqualTo(Object value) {
            addCriterion("ASSERT_JSON <>", value, "assertJson");
            return (Criteria) this;
        }

        public Criteria andAssertJsonGreaterThan(Object value) {
            addCriterion("ASSERT_JSON >", value, "assertJson");
            return (Criteria) this;
        }

        public Criteria andAssertJsonGreaterThanOrEqualTo(Object value) {
            addCriterion("ASSERT_JSON >=", value, "assertJson");
            return (Criteria) this;
        }

        public Criteria andAssertJsonLessThan(Object value) {
            addCriterion("ASSERT_JSON <", value, "assertJson");
            return (Criteria) this;
        }

        public Criteria andAssertJsonLessThanOrEqualTo(Object value) {
            addCriterion("ASSERT_JSON <=", value, "assertJson");
            return (Criteria) this;
        }

        public Criteria andAssertJsonIn(List<Object> values) {
            addCriterion("ASSERT_JSON in", values, "assertJson");
            return (Criteria) this;
        }

        public Criteria andAssertJsonNotIn(List<Object> values) {
            addCriterion("ASSERT_JSON not in", values, "assertJson");
            return (Criteria) this;
        }

        public Criteria andAssertJsonBetween(Object value1, Object value2) {
            addCriterion("ASSERT_JSON between", value1, value2, "assertJson");
            return (Criteria) this;
        }

        public Criteria andAssertJsonNotBetween(Object value1, Object value2) {
            addCriterion("ASSERT_JSON not between", value1, value2, "assertJson");
            return (Criteria) this;
        }

        public Criteria andAssertHtmlTextIsNull() {
            addCriterion("ASSERT_HTML_TEXT is null");
            return (Criteria) this;
        }

        public Criteria andAssertHtmlTextIsNotNull() {
            addCriterion("ASSERT_HTML_TEXT is not null");
            return (Criteria) this;
        }

        public Criteria andAssertHtmlTextEqualTo(Object value) {
            addCriterion("ASSERT_HTML_TEXT =", value, "assertHtmlText");
            return (Criteria) this;
        }

        public Criteria andAssertHtmlTextNotEqualTo(Object value) {
            addCriterion("ASSERT_HTML_TEXT <>", value, "assertHtmlText");
            return (Criteria) this;
        }

        public Criteria andAssertHtmlTextGreaterThan(Object value) {
            addCriterion("ASSERT_HTML_TEXT >", value, "assertHtmlText");
            return (Criteria) this;
        }

        public Criteria andAssertHtmlTextGreaterThanOrEqualTo(Object value) {
            addCriterion("ASSERT_HTML_TEXT >=", value, "assertHtmlText");
            return (Criteria) this;
        }

        public Criteria andAssertHtmlTextLessThan(Object value) {
            addCriterion("ASSERT_HTML_TEXT <", value, "assertHtmlText");
            return (Criteria) this;
        }

        public Criteria andAssertHtmlTextLessThanOrEqualTo(Object value) {
            addCriterion("ASSERT_HTML_TEXT <=", value, "assertHtmlText");
            return (Criteria) this;
        }

        public Criteria andAssertHtmlTextIn(List<Object> values) {
            addCriterion("ASSERT_HTML_TEXT in", values, "assertHtmlText");
            return (Criteria) this;
        }

        public Criteria andAssertHtmlTextNotIn(List<Object> values) {
            addCriterion("ASSERT_HTML_TEXT not in", values, "assertHtmlText");
            return (Criteria) this;
        }

        public Criteria andAssertHtmlTextBetween(Object value1, Object value2) {
            addCriterion("ASSERT_HTML_TEXT between", value1, value2, "assertHtmlText");
            return (Criteria) this;
        }

        public Criteria andAssertHtmlTextNotBetween(Object value1, Object value2) {
            addCriterion("ASSERT_HTML_TEXT not between", value1, value2, "assertHtmlText");
            return (Criteria) this;
        }

        public Criteria andAssertSqlIsNull() {
            addCriterion("ASSERT_SQL is null");
            return (Criteria) this;
        }

        public Criteria andAssertSqlIsNotNull() {
            addCriterion("ASSERT_SQL is not null");
            return (Criteria) this;
        }

        public Criteria andAssertSqlEqualTo(String value) {
            addCriterion("ASSERT_SQL =", value, "assertSql");
            return (Criteria) this;
        }

        public Criteria andAssertSqlNotEqualTo(String value) {
            addCriterion("ASSERT_SQL <>", value, "assertSql");
            return (Criteria) this;
        }

        public Criteria andAssertSqlGreaterThan(String value) {
            addCriterion("ASSERT_SQL >", value, "assertSql");
            return (Criteria) this;
        }

        public Criteria andAssertSqlGreaterThanOrEqualTo(String value) {
            addCriterion("ASSERT_SQL >=", value, "assertSql");
            return (Criteria) this;
        }

        public Criteria andAssertSqlLessThan(String value) {
            addCriterion("ASSERT_SQL <", value, "assertSql");
            return (Criteria) this;
        }

        public Criteria andAssertSqlLessThanOrEqualTo(String value) {
            addCriterion("ASSERT_SQL <=", value, "assertSql");
            return (Criteria) this;
        }

        public Criteria andAssertSqlLike(String value) {
            addCriterion("ASSERT_SQL like", value, "assertSql");
            return (Criteria) this;
        }

        public Criteria andAssertSqlNotLike(String value) {
            addCriterion("ASSERT_SQL not like", value, "assertSql");
            return (Criteria) this;
        }

        public Criteria andAssertSqlIn(List<String> values) {
            addCriterion("ASSERT_SQL in", values, "assertSql");
            return (Criteria) this;
        }

        public Criteria andAssertSqlNotIn(List<String> values) {
            addCriterion("ASSERT_SQL not in", values, "assertSql");
            return (Criteria) this;
        }

        public Criteria andAssertSqlBetween(String value1, String value2) {
            addCriterion("ASSERT_SQL between", value1, value2, "assertSql");
            return (Criteria) this;
        }

        public Criteria andAssertSqlNotBetween(String value1, String value2) {
            addCriterion("ASSERT_SQL not between", value1, value2, "assertSql");
            return (Criteria) this;
        }

        public Criteria andAssertSqlKeySetIsNull() {
            addCriterion("ASSERT_SQL_KEY_SET is null");
            return (Criteria) this;
        }

        public Criteria andAssertSqlKeySetIsNotNull() {
            addCriterion("ASSERT_SQL_KEY_SET is not null");
            return (Criteria) this;
        }

        public Criteria andAssertSqlKeySetEqualTo(String value) {
            addCriterion("ASSERT_SQL_KEY_SET =", value, "assertSqlKeySet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlKeySetNotEqualTo(String value) {
            addCriterion("ASSERT_SQL_KEY_SET <>", value, "assertSqlKeySet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlKeySetGreaterThan(String value) {
            addCriterion("ASSERT_SQL_KEY_SET >", value, "assertSqlKeySet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlKeySetGreaterThanOrEqualTo(String value) {
            addCriterion("ASSERT_SQL_KEY_SET >=", value, "assertSqlKeySet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlKeySetLessThan(String value) {
            addCriterion("ASSERT_SQL_KEY_SET <", value, "assertSqlKeySet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlKeySetLessThanOrEqualTo(String value) {
            addCriterion("ASSERT_SQL_KEY_SET <=", value, "assertSqlKeySet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlKeySetLike(String value) {
            addCriterion("ASSERT_SQL_KEY_SET like", value, "assertSqlKeySet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlKeySetNotLike(String value) {
            addCriterion("ASSERT_SQL_KEY_SET not like", value, "assertSqlKeySet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlKeySetIn(List<String> values) {
            addCriterion("ASSERT_SQL_KEY_SET in", values, "assertSqlKeySet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlKeySetNotIn(List<String> values) {
            addCriterion("ASSERT_SQL_KEY_SET not in", values, "assertSqlKeySet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlKeySetBetween(String value1, String value2) {
            addCriterion("ASSERT_SQL_KEY_SET between", value1, value2, "assertSqlKeySet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlKeySetNotBetween(String value1, String value2) {
            addCriterion("ASSERT_SQL_KEY_SET not between", value1, value2, "assertSqlKeySet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlValueSetIsNull() {
            addCriterion("ASSERT_SQL_VALUE_SET is null");
            return (Criteria) this;
        }

        public Criteria andAssertSqlValueSetIsNotNull() {
            addCriterion("ASSERT_SQL_VALUE_SET is not null");
            return (Criteria) this;
        }

        public Criteria andAssertSqlValueSetEqualTo(String value) {
            addCriterion("ASSERT_SQL_VALUE_SET =", value, "assertSqlValueSet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlValueSetNotEqualTo(String value) {
            addCriterion("ASSERT_SQL_VALUE_SET <>", value, "assertSqlValueSet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlValueSetGreaterThan(String value) {
            addCriterion("ASSERT_SQL_VALUE_SET >", value, "assertSqlValueSet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlValueSetGreaterThanOrEqualTo(String value) {
            addCriterion("ASSERT_SQL_VALUE_SET >=", value, "assertSqlValueSet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlValueSetLessThan(String value) {
            addCriterion("ASSERT_SQL_VALUE_SET <", value, "assertSqlValueSet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlValueSetLessThanOrEqualTo(String value) {
            addCriterion("ASSERT_SQL_VALUE_SET <=", value, "assertSqlValueSet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlValueSetLike(String value) {
            addCriterion("ASSERT_SQL_VALUE_SET like", value, "assertSqlValueSet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlValueSetNotLike(String value) {
            addCriterion("ASSERT_SQL_VALUE_SET not like", value, "assertSqlValueSet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlValueSetIn(List<String> values) {
            addCriterion("ASSERT_SQL_VALUE_SET in", values, "assertSqlValueSet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlValueSetNotIn(List<String> values) {
            addCriterion("ASSERT_SQL_VALUE_SET not in", values, "assertSqlValueSet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlValueSetBetween(String value1, String value2) {
            addCriterion("ASSERT_SQL_VALUE_SET between", value1, value2, "assertSqlValueSet");
            return (Criteria) this;
        }

        public Criteria andAssertSqlValueSetNotBetween(String value1, String value2) {
            addCriterion("ASSERT_SQL_VALUE_SET not between", value1, value2, "assertSqlValueSet");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table httptestcases
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}