package com.juntao.project_T.requestVo;

import java.io.Serializable;
import java.util.Date;

import com.juntao.commons.consts.ToStringObject;

public class InsertTestCase extends ToStringObject implements Serializable {

    private String creator;

    private Date created;

    private Long teamId;

    private String teamName;
    
    private String invType;

    private String invField;

    private Long projectId;

    private String projectName;

    private String projectVersion;

    private String apiName;

    private String apiCatalog;

    private String httpMethod;

    private String contentType;

    private String masterCookie;

    private String preUpdateSqlFlag;

    private String preUpdateSql;

    private String testPurpose;

    private String testCaseDescription;

    private String testCaseKeySet;

    private String testCaseValueSet;

    private String uploadFilePath;

    private String downloadFilePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column httptestcases.ASSERT_TYPE_SET
     *
     * @mbggenerated
     */
    private String assertTypeSet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column httptestcases.ASSERT_JSON
     *
     * @mbggenerated
     */
    private String assertJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column httptestcases.ASSERT_HTML_TEXT
     *
     * @mbggenerated
     */
    private String assertHtmlText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column httptestcases.ASSERT_SQL
     *
     * @mbggenerated
     */
    private String assertSql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column httptestcases.ASSERT_SQL_KEY_SET
     *
     * @mbggenerated
     */
    private String assertSqlKeySet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column httptestcases.ASSERT_SQL_VALUE_SET
     *
     * @mbggenerated
     */
    private String assertSqlValueSet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.CREATOR
     *
     * @return the value of httptestcases.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.CREATOR
     *
     * @param creator the value for httptestcases.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.CREATED
     *
     * @return the value of httptestcases.CREATED
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.CREATED
     *
     * @param created the value for httptestcases.CREATED
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.TEAM_ID
     *
     * @return the value of httptestcases.TEAM_ID
     *
     * @mbggenerated
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.TEAM_ID
     *
     * @param teamId the value for httptestcases.TEAM_ID
     *
     * @mbggenerated
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.TEAM_NAME
     *
     * @return the value of httptestcases.TEAM_NAME
     *
     * @mbggenerated
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.TEAM_NAME
     *
     * @param teamName the value for httptestcases.TEAM_NAME
     *
     * @mbggenerated
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.INV_TYPE
     *
     * @return the value of httptestcases.INV_TYPE
     *
     * @mbggenerated
     */
    public String getInvType() {
        return invType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.INV_TYPE
     *
     * @param invType the value for httptestcases.INV_TYPE
     *
     * @mbggenerated
     */
    public void setInvType(String invType) {
        this.invType = invType == null ? null : invType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.INV_FIELD
     *
     * @return the value of httptestcases.INV_FIELD
     *
     * @mbggenerated
     */
    public String getInvField() {
        return invField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.INV_FIELD
     *
     * @param invField the value for httptestcases.INV_FIELD
     *
     * @mbggenerated
     */
    public void setInvField(String invField) {
        this.invField = invField == null ? null : invField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.PROJECT_ID
     *
     * @return the value of httptestcases.PROJECT_ID
     *
     * @mbggenerated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.PROJECT_ID
     *
     * @param projectId the value for httptestcases.PROJECT_ID
     *
     * @mbggenerated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.PROJECT_NAME
     *
     * @return the value of httptestcases.PROJECT_NAME
     *
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.PROJECT_NAME
     *
     * @param projectName the value for httptestcases.PROJECT_NAME
     *
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.PROJECT_VERSION
     *
     * @return the value of httptestcases.PROJECT_VERSION
     *
     * @mbggenerated
     */
    public String getProjectVersion() {
        return projectVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.PROJECT_VERSION
     *
     * @param projectVersion the value for httptestcases.PROJECT_VERSION
     *
     * @mbggenerated
     */
    public void setProjectVersion(String projectVersion) {
        this.projectVersion = projectVersion == null ? null : projectVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.API_NAME
     *
     * @return the value of httptestcases.API_NAME
     *
     * @mbggenerated
     */
    public String getApiName() {
        return apiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.API_NAME
     *
     * @param apiName the value for httptestcases.API_NAME
     *
     * @mbggenerated
     */
    public void setApiName(String apiName) {
        this.apiName = apiName == null ? null : apiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.API_CATALOG
     *
     * @return the value of httptestcases.API_CATALOG
     *
     * @mbggenerated
     */
    public String getApiCatalog() {
        return apiCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.API_CATALOG
     *
     * @param apiCatalog the value for httptestcases.API_CATALOG
     *
     * @mbggenerated
     */
    public void setApiCatalog(String apiCatalog) {
        this.apiCatalog = apiCatalog == null ? null : apiCatalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.HTTP_METHOD
     *
     * @return the value of httptestcases.HTTP_METHOD
     *
     * @mbggenerated
     */
    public String getHttpMethod() {
        return httpMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.HTTP_METHOD
     *
     * @param httpMethod the value for httptestcases.HTTP_METHOD
     *
     * @mbggenerated
     */
    public void setHttpMethod(String httpMethod) {
        this.httpMethod = httpMethod == null ? null : httpMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.CONTENT_TYPE
     *
     * @return the value of httptestcases.CONTENT_TYPE
     *
     * @mbggenerated
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.CONTENT_TYPE
     *
     * @param contentType the value for httptestcases.CONTENT_TYPE
     *
     * @mbggenerated
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.MASTER_COOKIE
     *
     * @return the value of httptestcases.MASTER_COOKIE
     *
     * @mbggenerated
     */
    public String getMasterCookie() {
        return masterCookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.MASTER_COOKIE
     *
     * @param masterCookie the value for httptestcases.MASTER_COOKIE
     *
     * @mbggenerated
     */
    public void setMasterCookie(String masterCookie) {
        this.masterCookie = masterCookie == null ? null : masterCookie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.PRE_UPDATE_SQL_FLAG
     *
     * @return the value of httptestcases.PRE_UPDATE_SQL_FLAG
     *
     * @mbggenerated
     */
    public String getPreUpdateSqlFlag() {
        return preUpdateSqlFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.PRE_UPDATE_SQL_FLAG
     *
     * @param preUpdateSqlFlag the value for httptestcases.PRE_UPDATE_SQL_FLAG
     *
     * @mbggenerated
     */
    public void setPreUpdateSqlFlag(String preUpdateSqlFlag) {
        this.preUpdateSqlFlag = preUpdateSqlFlag == null ? null : preUpdateSqlFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.PRE_UPDATE_SQL
     *
     * @return the value of httptestcases.PRE_UPDATE_SQL
     *
     * @mbggenerated
     */
    public String getPreUpdateSql() {
        return preUpdateSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.PRE_UPDATE_SQL
     *
     * @param preUpdateSql the value for httptestcases.PRE_UPDATE_SQL
     *
     * @mbggenerated
     */
    public void setPreUpdateSql(String preUpdateSql) {
        this.preUpdateSql = preUpdateSql == null ? null : preUpdateSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.TEST_PURPOSE
     *
     * @return the value of httptestcases.TEST_PURPOSE
     *
     * @mbggenerated
     */
    public String getTestPurpose() {
        return testPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.TEST_PURPOSE
     *
     * @param testPurpose the value for httptestcases.TEST_PURPOSE
     *
     * @mbggenerated
     */
    public void setTestPurpose(String testPurpose) {
        this.testPurpose = testPurpose == null ? null : testPurpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.TEST_CASE_DESCRIPTION
     *
     * @return the value of httptestcases.TEST_CASE_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getTestCaseDescription() {
        return testCaseDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.TEST_CASE_DESCRIPTION
     *
     * @param testCaseDescription the value for httptestcases.TEST_CASE_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setTestCaseDescription(String testCaseDescription) {
        this.testCaseDescription = testCaseDescription == null ? null : testCaseDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.TEST_CASE_KEY_SET
     *
     * @return the value of httptestcases.TEST_CASE_KEY_SET
     *
     * @mbggenerated
     */
    public String getTestCaseKeySet() {
        return testCaseKeySet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.TEST_CASE_KEY_SET
     *
     * @param testCaseKeySet the value for httptestcases.TEST_CASE_KEY_SET
     *
     * @mbggenerated
     */
    public void setTestCaseKeySet(String testCaseKeySet) {
        this.testCaseKeySet = testCaseKeySet == null ? null : testCaseKeySet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.TEST_CASE_VALUE_SET
     *
     * @return the value of httptestcases.TEST_CASE_VALUE_SET
     *
     * @mbggenerated
     */
    public String getTestCaseValueSet() {
        return testCaseValueSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.TEST_CASE_VALUE_SET
     *
     * @param testCaseValueSet the value for httptestcases.TEST_CASE_VALUE_SET
     *
     * @mbggenerated
     */
    public void setTestCaseValueSet(String testCaseValueSet) {
        this.testCaseValueSet = testCaseValueSet == null ? null : testCaseValueSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.UPLOAD_FILE_PATH
     *
     * @return the value of httptestcases.UPLOAD_FILE_PATH
     *
     * @mbggenerated
     */
    public String getUploadFilePath() {
        return uploadFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.UPLOAD_FILE_PATH
     *
     * @param uploadFilePath the value for httptestcases.UPLOAD_FILE_PATH
     *
     * @mbggenerated
     */
    public void setUploadFilePath(String uploadFilePath) {
        this.uploadFilePath = uploadFilePath == null ? null : uploadFilePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.DOWNLOAD_FILE_PATH
     *
     * @return the value of httptestcases.DOWNLOAD_FILE_PATH
     *
     * @mbggenerated
     */
    public String getDownloadFilePath() {
        return downloadFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.DOWNLOAD_FILE_PATH
     *
     * @param downloadFilePath the value for httptestcases.DOWNLOAD_FILE_PATH
     *
     * @mbggenerated
     */
    public void setDownloadFilePath(String downloadFilePath) {
        this.downloadFilePath = downloadFilePath == null ? null : downloadFilePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.ASSERT_TYPE_SET
     *
     * @return the value of httptestcases.ASSERT_TYPE_SET
     *
     * @mbggenerated
     */
    public String getAssertTypeSet() {
        return assertTypeSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.ASSERT_TYPE_SET
     *
     * @param assertTypeSet the value for httptestcases.ASSERT_TYPE_SET
     *
     * @mbggenerated
     */
    public void setAssertTypeSet(String assertTypeSet) {
        this.assertTypeSet = assertTypeSet == null ? null : assertTypeSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.ASSERT_JSON
     *
     * @return the value of httptestcases.ASSERT_JSON
     *
     * @mbggenerated
     */
    public String getAssertJson() {
        return assertJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.ASSERT_JSON
     *
     * @param assertJson the value for httptestcases.ASSERT_JSON
     *
     * @mbggenerated
     */
    public void setAssertJson(String assertJson) {
        this.assertJson = assertJson == null ? null : assertJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.ASSERT_HTML_TEXT
     *
     * @return the value of httptestcases.ASSERT_HTML_TEXT
     *
     * @mbggenerated
     */
    public String getAssertHtmlText() {
        return assertHtmlText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.ASSERT_HTML_TEXT
     *
     * @param assertHtmlText the value for httptestcases.ASSERT_HTML_TEXT
     *
     * @mbggenerated
     */
    public void setAssertHtmlText(String assertHtmlText) {
        this.assertHtmlText = assertHtmlText == null ? null : assertHtmlText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.ASSERT_SQL
     *
     * @return the value of httptestcases.ASSERT_SQL
     *
     * @mbggenerated
     */
    public String getAssertSql() {
        return assertSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.ASSERT_SQL
     *
     * @param assertSql the value for httptestcases.ASSERT_SQL
     *
     * @mbggenerated
     */
    public void setAssertSql(String assertSql) {
        this.assertSql = assertSql == null ? null : assertSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.ASSERT_SQL_KEY_SET
     *
     * @return the value of httptestcases.ASSERT_SQL_KEY_SET
     *
     * @mbggenerated
     */
    public String getAssertSqlKeySet() {
        return assertSqlKeySet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.ASSERT_SQL_KEY_SET
     *
     * @param assertSqlKeySet the value for httptestcases.ASSERT_SQL_KEY_SET
     *
     * @mbggenerated
     */
    public void setAssertSqlKeySet(String assertSqlKeySet) {
        this.assertSqlKeySet = assertSqlKeySet == null ? null : assertSqlKeySet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column httptestcases.ASSERT_SQL_VALUE_SET
     *
     * @return the value of httptestcases.ASSERT_SQL_VALUE_SET
     *
     * @mbggenerated
     */
    public String getAssertSqlValueSet() {
        return assertSqlValueSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column httptestcases.ASSERT_SQL_VALUE_SET
     *
     * @param assertSqlValueSet the value for httptestcases.ASSERT_SQL_VALUE_SET
     *
     * @mbggenerated
     */
    public void setAssertSqlValueSet(String assertSqlValueSet) {
        this.assertSqlValueSet = assertSqlValueSet == null ? null : assertSqlValueSet.trim();
    }

    
    @Override
    public int hashCode() {
        final int prime = 30;
        int result = 1;
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        result = prime * result + ((getTeamId() == null) ? 0 : getTeamId().hashCode());
        result = prime * result + ((getTeamName() == null) ? 0 : getTeamName().hashCode());
        result = prime * result + ((getInvType() == null) ? 0 : getInvType().hashCode());
        result = prime * result + ((getInvField() == null) ? 0 : getInvField().hashCode());
        result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
        result = prime * result + ((getProjectName() == null) ? 0 : getProjectName().hashCode());
        result = prime * result + ((getProjectVersion() == null) ? 0 : getProjectVersion().hashCode());
        result = prime * result + ((getApiName() == null) ? 0 : getApiName().hashCode());
        result = prime * result + ((getApiCatalog() == null) ? 0 : getApiCatalog().hashCode());
        result = prime * result + ((getHttpMethod() == null) ? 0 : getHttpMethod().hashCode());
        result = prime * result + ((getContentType() == null) ? 0 : getContentType().hashCode());
        result = prime * result + ((getMasterCookie() == null) ? 0 : getMasterCookie().hashCode());
        result = prime * result + ((getPreUpdateSqlFlag() == null) ? 0 : getPreUpdateSqlFlag().hashCode());
        result = prime * result + ((getPreUpdateSql() == null) ? 0 : getPreUpdateSql().hashCode());
        result = prime * result + ((getTestPurpose() == null) ? 0 : getTestPurpose().hashCode());
        result = prime * result + ((getTestCaseDescription() == null) ? 0 : getTestCaseDescription().hashCode());
        result = prime * result + ((getTestCaseKeySet() == null) ? 0 : getTestCaseKeySet().hashCode());
        result = prime * result + ((getTestCaseValueSet() == null) ? 0 : getTestCaseValueSet().hashCode());
        result = prime * result + ((getUploadFilePath() == null) ? 0 : getUploadFilePath().hashCode());
        result = prime * result + ((getDownloadFilePath() == null) ? 0 : getDownloadFilePath().hashCode());
        result = prime * result + ((getAssertTypeSet() == null) ? 0 : getAssertTypeSet().hashCode());
        result = prime * result + ((getAssertJson() == null) ? 0 : getAssertJson().hashCode());
        result = prime * result + ((getAssertHtmlText() == null) ? 0 : getAssertHtmlText().hashCode());
        result = prime * result + ((getAssertSql() == null) ? 0 : getAssertSql().hashCode());
        result = prime * result + ((getAssertSqlKeySet() == null) ? 0 : getAssertSqlKeySet().hashCode());
        result = prime * result + ((getAssertSqlValueSet() == null) ? 0 : getAssertSqlValueSet().hashCode());
        return result;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table httptestcases
     *
     * @mbggenerated
     */
//    @Override
//    public String toString() {
//        StringBuilder sb = new StringBuilder();
//        sb.append(getClass().getSimpleName());
//        sb.append(" [");
//        sb.append("Hash = ").append(hashCode());
//        sb.append(", creator=").append(creator);
//        sb.append(", created=").append(created);
//        sb.append(", teamId=").append(teamId);
//        sb.append(", teamName=").append(teamName);
//        sb.append(", invType=").append(invType);
//        sb.append(", invField=").append(invField);
//        sb.append(", projectId=").append(projectId);
//        sb.append(", projectName=").append(projectName);
//        sb.append(", projectVersion=").append(projectVersion);
//        sb.append(", apiName=").append(apiName);
//        sb.append(", apiCatalog=").append(apiCatalog);
//        sb.append(", httpMethod=").append(httpMethod);
//        sb.append(", contentType=").append(contentType);
//        sb.append(", masterCookie=").append(masterCookie);
//        sb.append(", preUpdateSqlFlag=").append(preUpdateSqlFlag);
//        sb.append(", preUpdateSql=").append(preUpdateSql);
//        sb.append(", testPurpose=").append(testPurpose);
//        sb.append(", testCaseDescription=").append(testCaseDescription);
//        sb.append(", testCaseKeySet=").append(testCaseKeySet);
//        sb.append(", testCaseValueSet=").append(testCaseValueSet);
//        sb.append(", uploadFilePath=").append(uploadFilePath);
//        sb.append(", downloadFilePath=").append(downloadFilePath);
//        sb.append(", assertTypeSet=").append(assertTypeSet);
//        sb.append(", assertJson=").append(assertJson);
//        sb.append(", assertHtmlText=").append(assertHtmlText);
//        sb.append(", assertSql=").append(assertSql);
//        sb.append(", assertSqlKeySet=").append(assertSqlKeySet);
//        sb.append(", assertSqlValueSet=").append(assertSqlValueSet);
//        sb.append(", serialVersionUID=").append(serialVersionUID);
//        sb.append("]");
//        return sb.toString();
//    }
}